baseURL = "https://doxmx.org/"
languageCode = "en-us"
title = "DOxMX"
theme = "beautifulhugo"

[Author]
    name = "DOxMX"
    website = "https://doxmx.org/"


[Params]
    rss = true
    wordCount = true
    socialShare = true
    showRelatedPosts = true

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
